eureka:
  client:
    region: region-1
    service-url:
      zone1: http://localhost:8761/eureka/
      zone2: http://localhost:8762/eureka/
    availability-zones:
      region-1: zone1,zone2
    prefer-same-zone-eureka: true
spring:
  profiles:
    active: zone1
  application:
    name: auth-service